### ISSUE TITLE
Central Management - No Way to Hide Email Activation On Login Screen

### ISSUE THREAD

**Issue by ryanrichter94** [chocolatey/chocolatey-licensed-issues#270]
### What You Are Seeing?
Their is currently no way of getting rid of the `Not a member yet? Email activation` section on the CCM login page.

### What is Expected?
I would assume this would be hidden when you uncheck the user management setting `Allow users to register to the system`

### How Did You Get This To Happen? (Steps to Reproduce)
1. Be running CCM 0.6.3
1. Go into settings and disable `Allow users to register to the system`
1. On the CCM login screen you'll still see `Not a member yet? Email activation` under the Log in button.
### Screenshots
![image](https://user-images.githubusercontent.com/57045117/135630337-124a2d3e-fb78-49ce-a3c6-43c8afba37bd.png)
### References

* [ZenDesk Ticket](https://chocolatey.zendesk.com/agent/tickets/11787)

┆Issue is synchronized with this [Gitlab issue](https://gitlab.com/chocolatey/central-management/choco-licensed-management-ui/-/issues/700) by [Unito](https://www.unito.io)
┆Milestone: 0.9.0

**Comment by gep13** [comment]
Within CCM 0.8.0 and earlier, by default, when looking at the CCM Login screen, you would have seen the following:

![image](https://user-images.githubusercontent.com/1271146/173807577-13c06141-6cab-4990-a82f-cbba6edb0ecc.png)

After disabling the `Allow users to register to the system` checkbox in the Administration Settings screen, the login page would show the following:

![image](https://user-images.githubusercontent.com/1271146/173807757-6c60ab60-74bd-48e7-a1cf-84ae20da33f6.png)

**NOTE:** There is still `Not a member yet?` text being shown, which isn't very useful.

Starting with 0.9.0, when you first visit the login screen, you will see the following:

![image](https://user-images.githubusercontent.com/1271146/173809985-399492d1-3f9e-47d2-a857-bd570bddf9fc.png)

And then, when the `Allow users to register to the system` checkbox in the Administration Settings screen is disabled, you will see the following:

![image](https://user-images.githubusercontent.com/1271146/173809962-be33e6cb-8a1f-47c1-9010-327522cd332f.png)


**NOTE:** The email activation link is still required, since when a user is being created through the administration section, it is possible to still require emails to be confirmed, therefore a link to re-sent this activation is still required.
